import {stringify} from 'yaml';
import {parseLinterConfig} from './loader';
import {RuleConfig, RulesConfig} from './types';

/**
 * Keys upstream data.json keeps for UI state only (F01 R3). They stay in
 * data.json by design and are deliberately not migrated to linter.yaml.
 */
const UI_STATE_KEYS = new Set([
  'lintOnSave',
  'displayChanged',
  'suppressMessageWhenNoChange',
  'suppressLintAllFilesConfirmationModal',
  'suppressLintAllFilesInFolderConfirmationModal',
  'settingsConvertedToConfigKeyValues',
  'recordLintOnSaveLogs',
  'lintOnFileChange',
  'displayLintOnFileChangeNotice',
  'linterLocale',
  'logLevel',
]);

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isStringArray(value: unknown): value is string[] {
  return Array.isArray(value) && value.every((v) => typeof v === 'string');
}

/**
 * Map an upstream data.json (LinterSettings shape from src/settings-data.ts)
 * to a linter.yaml text. Conservative: `ruleConfigs` entries become
 * `defaults.rules`, `foldersToIgnore` becomes `ignore.folders`, UI-state keys
 * stay behind in data.json, and everything else lands in a commented
 * "unmapped" block instead of being dropped. Idempotent: input that already
 * parses as a valid linter.yaml is returned unchanged.
 */
export function migrateDataJson(dataJson: string): string {
  if (parseLinterConfig(dataJson).ok) {
    return dataJson;
  }

  let data: unknown;
  try {
    data = JSON.parse(dataJson);
  } catch (err) {
    throw new Error(`data.json is neither a valid linter.yaml nor valid JSON: ${(err as Error).message}`);
  }
  if (!isPlainObject(data)) {
    throw new Error('data.json must be a JSON object');
  }

  const unmapped: Record<string, unknown> = {};
  const rules: RulesConfig = {};

  if ('ruleConfigs' in data) {
    const ruleConfigs = data.ruleConfigs;
    if (isPlainObject(ruleConfigs)) {
      for (const [ruleId, options] of Object.entries(ruleConfigs)) {
        const mappable = isPlainObject(options) &&
          (!('enabled' in options) || typeof options.enabled === 'boolean');
        if (mappable) {
          rules[ruleId] = {...options} as RuleConfig;
        } else {
          unmapped[`ruleConfigs.${ruleId}`] = options;
        }
      }
    } else if (ruleConfigs !== undefined) {
      unmapped['ruleConfigs'] = ruleConfigs;
    }
  }

  let ignoreFolders: string[] | undefined;
  if ('foldersToIgnore' in data) {
    if (isStringArray(data.foldersToIgnore)) {
      ignoreFolders = data.foldersToIgnore;
    } else {
      unmapped['foldersToIgnore'] = data.foldersToIgnore;
    }
  }

  for (const [key, value] of Object.entries(data)) {
    if (key === 'ruleConfigs' || key === 'foldersToIgnore' || UI_STATE_KEYS.has(key)) {
      continue;
    }
    unmapped[key] = value;
  }

  const config: Record<string, unknown> = {version: 1};
  if (Object.keys(rules).length > 0) {
    config.defaults = {rules};
  }
  if (ignoreFolders && ignoreFolders.length > 0) {
    config.ignore = {folders: ignoreFolders};
  }

  const lines: string[] = [
    '# linter.yaml generated by lappe-linter from data.json.',
    '# UI-only settings (save/notice/locale/log toggles) stay in data.json by design.',
    stringify(config).trimEnd(),
  ];

  const unmappedKeys = Object.keys(unmapped);
  if (unmappedKeys.length > 0) {
    lines.push('');
    lines.push('# unmapped: the data.json settings below have no linter.yaml equivalent yet.');
    lines.push('# They were carried over as comments so nothing is dropped silently.');
    for (const key of unmappedKeys) {
      lines.push(`# ${key}: ${JSON.stringify(unmapped[key])}`);
    }
  }

  return lines.join('\n') + '\n';
}
