import {CoreRule, CoreRuleExample, getRules} from './rule';

/**
 * Disposable test-file content built from each registered rule's examples[],
 * so the fixtures never drift from the rule's own test corpus. The Obsidian
 * plugin writes these into _archive/<date>-lappe-linter-test-files/ and the
 * CLI can reuse the same content later. Pure: no vault, no filesystem.
 */

export interface RuleFixture {
  /** File name to write, `<rule-id>.md`. */
  name: string;
  /** Full file content: the messy example input plus the explanation line. */
  content: string;
  /** One-line explanation of what linting this file demonstrates. */
  explains: string;
}

function splitFrontmatter(text: string): {frontmatter: string; body: string} {
  if (text.startsWith('---\n')) {
    const end = text.indexOf('\n---\n', 3);
    if (end !== -1) {
      return {frontmatter: text.slice(0, end + 5), body: text.slice(end + 5)};
    }
  }
  return {frontmatter: '', body: text};
}

/**
 * The example a fixture is built from: prefer one that runs on default
 * options, since vault linting applies the resolved config rather than the
 * example's bespoke options.
 */
function demoExample(rule: CoreRule): CoreRuleExample {
  const examples = rule.examples ?? [];
  return examples.find((example) => example.options === undefined) ?? examples[0];
}

function rulesWithExamples(): CoreRule[] {
  return getRules()
      .filter((rule) => (rule.examples ?? []).length > 0)
      .sort((a, b) => a.id.localeCompare(b.id));
}

/**
 * One 'before' fixture per registered rule that carries examples. The
 * explanation line lands in the body (after any frontmatter, so frontmatter
 * rules still see their block at the top of the file).
 */
export function ruleFixtures(): RuleFixture[] {
  return rulesWithExamples().map((rule) => {
    const explains = `Demonstrates ${rule.id}: ${rule.description}`;
    const {frontmatter, body} = splitFrontmatter(demoExample(rule).before);
    return {
      name: `${rule.id}.md`,
      content: `${frontmatter}${explains}\n\n${body}`,
      explains,
    };
  });
}

/**
 * One combined messy note. The frontmatter block comes from a frontmatter
 * rule's example (unsorted keys and values exercise the frontmatter rules in
 * one pass); the body stacks each content rule's example input under a
 * heading naming the rule.
 */
export function kitchenSinkFixture(): string {
  const rules = rulesWithExamples();
  const frontmatterRule = rules.find(
      (rule) => rule.category === 'frontmatter' && splitFrontmatter(demoExample(rule).before).frontmatter !== '');
  const header = frontmatterRule ? splitFrontmatter(demoExample(frontmatterRule).before).frontmatter : '';

  const sections: string[] = ['One messy note exercising the core rules at once. Lint it and diff.'];
  for (const rule of rules) {
    if (rule.category !== 'content') {
      continue;
    }
    const {body} = splitFrontmatter(demoExample(rule).before);
    if (body.trim() === '') {
      continue;
    }
    sections.push(`## ${rule.id}`, body.trimEnd());
  }
  return `${header}${sections.join('\n\n')}\n`;
}

/** README dropped next to the fixtures explaining what the folder is for. */
export function testFilesReadme(folder: string): string {
  return [
    '# lappe-linter test files',
    '',
    `This folder (${folder}) is a disposable fixture set generated by lappe-linter. Delete it whenever you like; regenerating creates a fresh dated folder.`,
    '',
    'Each `<rule-id>.md` file is messy input demonstrating what that rule fixes, built from the rule\'s own worked examples. `kitchen-sink.md` combines them into one note.',
    '',
    'Lint the files (lint-all, lint-all-files-in-folder, or per file) and diff the result to see each rule\'s effect. Rules only run when enabled in linter.yaml, and this folder must not be listed under ignore.folders for the fixtures to lint.',
    '',
  ].join('\n');
}
